### ISSUE TITLE
How to concatenate 2 vars

### ISSUE THREAD

**Issue by Snake1980** [custom-cards/config-template-card#10]
I'm trying to create a custom card for my blinds.
I need to view entity name as "friendly_name (percentage %)".
(I'm getting % number from another entity) 

This is my card

```
entities:
  - input_number.posizione_tapparella_camera
  - cover.matrimoniale
variables:
  - 'states["cover.matrimoniale"].name'
  - 'states["input_number.posizione_tapparella_camera"].state'
card:
  entities:
    - name: '${vars[0] + " (" + vars[1] + " %)"}'
      entity: cover.matrimoniale
  type: '${''custom:hui-entities-card''}'
type: 'custom:config-template-card'
```

But this is the result

![image](https://user-images.githubusercontent.com/7205371/56323965-c838b580-616d-11e9-97cb-5f61286dac71.png)

How can I solve this ?
If I use this template for entity name it shows the correct name

` - name: '${vars[0]}'`

Another question...
How can I cast % value as integer ?
{vars[1] | int}  not works

**Comment by iantrich** [comment]
I'm guessing you want the friendly name. You should try the following:

```yaml
'states["cover.matrimoniale"].attributes.friendly_name'
```

**Comment by Snake1980** [comment]
I tried with friendly_name and name...same result
If I join name and percentage number, the name is showed as undefined

**Comment by iantrich** [comment]
`attributes` is the key thing

**Comment by Snake1980** [comment]
Thank you! This solved first problem. Now I can see friendly_name and percentage.

This is new code...

```
variables:
  - 'states["cover.matrimoniale"].attributes.friendly_name'
  - 'states["input_number.posizione_tapparella_camera"].state'
type: 'custom:config-template-card'
card:
  type: '${''custom:hui-entities-card''}'
  entities:
    - entity: cover.matrimoniale
      name: '${vars[0] + " (" + vars[1] + " %)"}'
entities:
  - input_number.posizione_tapparella_camera
  - cover.matrimoniale
```

![image](https://user-images.githubusercontent.com/7205371/56396659-29c95480-6240-11e9-931b-15e990965ec6.png)

Second problem... is it possible to cast percentage number as integer
