### ISSUE TITLE
HA border/shadow conflic

### ISSUE THREAD

**Issue by SeLLeRoNe** [custom-cards/config-template-card#8]
Here the requested example:
With the problem:
```
title: Temperatures
icon: mdi:thermometer
panel: true
theme: darkblue
path: temperatures
cards:
  - type: vertical-stack
    cards:
      - !include ../cards/compact_custom_header_main.yaml
      - type: custom:layout-card
        layout: vertical
        cards:
          - type: vertical-stack
            cards:
              - type: custom:card-modder
                style:
                  --paper-card-background-color: 'rgba(11, 11, 11, 0.40)'
                  text-align: center
                  color: silver
                  font-size: 25px
                  border-radius: 20px
                  border: solid 1px rgba(100,100,100,0.3)
                  box-shadow: 3px 3px rgba(0,0,0,0.4)
                  background-image: url("/local/cardbackK.png")
                  background-repeat: no-repeat
                  background-color: rgba(50,50,50,0.3)
                  background-size: 100% 48px
                card:
                  content: Temperatures
                  type: markdown
          - type: custom:vertical-stack-in-card
            cards:
              - type: horizontal-stack
                cards:
                  - type: custom:config-template-card
                    entities:
                      - sensor.dark_sky_temperature
                    config:
                      type: custom:mini-graph-card
                      name: Outside
                      icon: "${states['sensor.dark_sky_temperature'].state > 15 ? 'fas:thermometer-half' : 'fas:thermometer-quarter'}"
                      name_adaptive_color: true
                      icon_adaptive_color: true
                      more_info: false
                      height: 150
                      line_width: 4
                      hours_to_show: 24
                      points_per_hour: 0.50
                      group: false
                      hour24: true
                      animate: true
                      decimals: 1
                      align_state: center
                      show:
                        name: true
                        icon: true
                        state: true
                        graph: false
                        fill: false
                        points: false
                        legend: false
                        extrema: true
                        labels: false
                      entities:
                        - entity: sensor.dark_sky_temperature
                          color: '#FF8000'
                          show_indicator: true
                  - type: custom:config-template-card
                    entities:
                      - sensor.dark_sky_temperature
                    config:
                      type: custom:mini-graph-card
                      name: Outside
                      icon: "${states['sensor.dark_sky_temperature'].state > 15 ? 'fas:thermometer-half' : 'fas:thermometer-quarter'}"
                      name_adaptive_color: true
                      icon_adaptive_color: true
                      more_info: false
                      height: 150
                      line_width: 4
                      hours_to_show: 24
                      points_per_hour: 0.50
                      group: false
                      hour24: true
                      animate: true
                      decimals: 1
                      align_state: center
                      show:
                        name: true
                        icon: true
                        state: true
                        graph: false
                        fill: false
                        points: false
                        legend: false
                        extrema: true
                        labels: false
                      entities:
                        - entity: sensor.dark_sky_temperature
                          color: '#FF8000'
                          show_indicator: true
                  - type: custom:config-template-card
                    entities:
                      - sensor.dark_sky_temperature
                    config:
                      type: custom:mini-graph-card
                      name: Outside
                      icon: "${states['sensor.dark_sky_temperature'].state > 15 ? 'fas:thermometer-half' : 'fas:thermometer-quarter'}"
                      name_adaptive_color: true
                      icon_adaptive_color: true
                      more_info: false
                      height: 150
                      line_width: 4
                      hours_to_show: 24
                      points_per_hour: 0.50
                      group: false
                      hour24: true
                      animate: true
                      decimals: 1
                      align_state: center
                      show:
                        name: true
                        icon: true
                        state: true
                        graph: false
                        fill: false
                        points: false
                        legend: false
                        extrema: true
                        labels: false
                      entities:
                        - entity: sensor.dark_sky_temperature
                          color: '#FF8000'
                          show_indicator: true
              - type: horizontal-stack
                cards:
                  - type: custom:config-template-card
                    entities:
                      - sensor.dark_sky_temperature
                    config:
                      type: custom:mini-graph-card
                      name: Outside
                      icon: "${states['sensor.dark_sky_temperature'].state > 15 ? 'fas:thermometer-half' : 'fas:thermometer-quarter'}"
                      name_adaptive_color: true
                      icon_adaptive_color: true
                      more_info: false
                      height: 150
                      line_width: 4
                      hours_to_show: 24
                      points_per_hour: 0.50
                      group: false
                      hour24: true
                      animate: true
                      decimals: 1
                      align_state: center
                      show:
                        name: true
                        icon: true
                        state: true
                        graph: false
                        fill: false
                        points: false
                        legend: false
                        extrema: true
                        labels: false
                      entities:
                        - entity: sensor.dark_sky_temperature
                          color: '#FF8000'
                          show_indicator: true
              - type: horizontal-stack
                cards:
                  - type: custom:config-template-card
                    entities:
                      - sensor.dark_sky_temperature
                    config:
                      type: custom:mini-graph-card
                      name: Outside
                      icon: "${states['sensor.dark_sky_temperature'].state > 15 ? 'fas:thermometer-half' : 'fas:thermometer-quarter'}"
                      name_adaptive_color: true
                      icon_adaptive_color: true
                      more_info: false
                      height: 150
                      line_width: 4
                      hours_to_show: 24
                      points_per_hour: 0.50
                      group: false
                      hour24: true
                      animate: true
                      decimals: 1
                      align_state: center
                      show:
                        name: true
                        icon: true
                        state: true
                        graph: false
                        fill: false
                        points: false
                        legend: false
                        extrema: true
                        labels: false
                      entities:
                        - entity: sensor.dark_sky_temperature
                          color: '#FF8000'
                          show_indicator: true
                  - type: custom:config-template-card
                    entities:
                      - sensor.dark_sky_temperature
                    config:
                      type: custom:mini-graph-card
                      name: Outside
                      icon: "${states['sensor.dark_sky_temperature'].state > 15 ? 'fas:thermometer-half' : 'fas:thermometer-quarter'}"
                      name_adaptive_color: true
                      icon_adaptive_color: true
                      more_info: false
                      height: 150
                      line_width: 4
                      hours_to_show: 24
                      points_per_hour: 0.50
                      group: false
                      hour24: true
                      animate: true
                      decimals: 1
                      align_state: center
                      show:
                        name: true
                        icon: true
                        state: true
                        graph: false
                        fill: false
                        points: false
                        legend: false
                        extrema: true
                        labels: false
                      entities:
                        - entity: sensor.dark_sky_temperature
                          color: '#FF8000'
                          show_indicator: true
                  - type: custom:config-template-card
                    entities:
                      - sensor.dark_sky_temperature
                    config:
                      type: custom:mini-graph-card
                      name: Outside
                      icon: "${states['sensor.dark_sky_temperature'].state > 15 ? 'fas:thermometer-half' : 'fas:thermometer-quarter'}"
                      name_adaptive_color: true
                      icon_adaptive_color: true
                      more_info: false
                      height: 150
                      line_width: 4
                      hours_to_show: 24
                      points_per_hour: 0.50
                      group: false
                      hour24: true
                      animate: true
                      decimals: 1
                      align_state: center
                      show:
                        name: true
                        icon: true
                        state: true
                        graph: false
                        fill: false
                        points: false
                        legend: false
                        extrema: true
                        labels: false
                      entities:
                        - entity: sensor.dark_sky_temperature
                          color: '#FF8000'
                          show_indicator: true
              - type: custom:mini-graph-card
                name: Temperature 48h
                icon: fas:thermometer-half
                name_adaptive_color: true
                icon_adaptive_color: true
                more_info: false
                group: false
                height: 150
                line_width: 4
                hours_to_show: 24
                points_per_hour: 0.5
                hour24: true
                animate: true
                decimals: 1
                align_state: center
                show:
                  name: false
                  icon: false
                  state: false
                  graph: line
                  fill: false
                  points: false
                  legend: true
                  extrema: false
                  labels: false
                entities:
                  - entity: sensor.dark_sky_temperature
                    name: Outside
                    color: '#FF8000'
                  - entity: sensor.dark_sky_temperature
                    name: Master Bedroom
                    color: '#0080FF'
                  - entity: sensor.dark_sky_temperature
                    name: Living Room
                    color: '#FF3333'
                  - entity: sensor.dark_sky_temperature
                    name: Office
                    color: '#7F00FF'
                  - entity: sensor.dark_sky_temperature
                    name: Bedroom
                    color: '#00FF00'
                  - entity: sensor.dark_sky_temperature
                    name: Bathroom
                    color: '#33FF99'
```

Without the problem:
```
title: Temperatures
icon: mdi:thermometer
panel: true
theme: darkblue
path: temperatures_old
cards:
  - type: vertical-stack
    cards:
      - !include ../cards/compact_custom_header_main.yaml
      - type: custom:layout-card
        layout: vertical
        cards:
          - type: vertical-stack
            cards:
              - type: custom:card-modder
                style:
                  --paper-card-background-color: 'rgba(11, 11, 11, 0.40)'
                  text-align: center
                  color: silver
                  font-size: 25px
                  border-radius: 20px
                  border: solid 1px rgba(100,100,100,0.3)
                  box-shadow: 3px 3px rgba(0,0,0,0.4)
                  background-image: url("/local/cardbackK.png")
                  background-repeat: no-repeat
                  background-color: rgba(50,50,50,0.3)
                  background-size: 100% 48px
                card:
                  content: Temperatures
                  type: markdown
          - type: custom:vertical-stack-in-card
            cards:
              - type: horizontal-stack
                cards:
                  - type: custom:mini-graph-card
                    name: Outside
                    icon: "${states['sensor.dark_sky_temperature'].state > 15 ? 'fas:thermometer-half' : 'fas:thermometer-quarter'}"
                    name_adaptive_color: true
                    icon_adaptive_color: true
                    more_info: false
                    height: 150
                    line_width: 4
                    hours_to_show: 24
                    points_per_hour: 0.50
                    group: false
                    hour24: true
                    animate: true
                    decimals: 1
                    align_state: center
                    show:
                      name: true
                      icon: true
                      state: true
                      graph: false
                      fill: false
                      points: false
                      legend: false
                      extrema: true
                      labels: false
                    entities:
                      - entity: sensor.dark_sky_temperature
                        color: '#FF8000'
                        show_indicator: true
                  - type: custom:mini-graph-card
                    name: Outside
                    icon: "${states['sensor.dark_sky_temperature'].state > 15 ? 'fas:thermometer-half' : 'fas:thermometer-quarter'}"
                    name_adaptive_color: true
                    icon_adaptive_color: true
                    more_info: false
                    height: 150
                    line_width: 4
                    hours_to_show: 24
                    points_per_hour: 0.50
                    group: false
                    hour24: true
                    animate: true
                    decimals: 1
                    align_state: center
                    show:
                      name: true
                      icon: true
                      state: true
                      graph: false
                      fill: false
                      points: false
                      legend: false
                      extrema: true
                      labels: false
                    entities:
                      - entity: sensor.dark_sky_temperature
                        color: '#FF8000'
                        show_indicator: true
                  - type: custom:mini-graph-card
                    name: Outside
                    icon: "${states['sensor.dark_sky_temperature'].state > 15 ? 'fas:thermometer-half' : 'fas:thermometer-quarter'}"
                    name_adaptive_color: true
                    icon_adaptive_color: true
                    more_info: false
                    height: 150
                    line_width: 4
                    hours_to_show: 24
                    points_per_hour: 0.50
                    group: false
                    hour24: true
                    animate: true
                    decimals: 1
                    align_state: center
                    show:
                      name: true
                      icon: true
                      state: true
                      graph: false
                      fill: false
                      points: false
                      legend: false
                      extrema: true
                      labels: false
                    entities:
                      - entity: sensor.dark_sky_temperature
                        color: '#FF8000'
                        show_indicator: true
              - type: horizontal-stack
                cards:
                  - type: custom:mini-graph-card
                    name: Outside
                    icon: "${states['sensor.dark_sky_temperature'].state > 15 ? 'fas:thermometer-half' : 'fas:thermometer-quarter'}"
                    name_adaptive_color: true
                    icon_adaptive_color: true
                    more_info: false
                    height: 150
                    line_width: 4
                    hours_to_show: 24
                    points_per_hour: 0.50
                    group: false
                    hour24: true
                    animate: true
                    decimals: 1
                    align_state: center
                    show:
                      name: true
                      icon: true
                      state: true
                      graph: false
                      fill: false
                      points: false
                      legend: false
                      extrema: true
                      labels: false
                    entities:
                      - entity: sensor.dark_sky_temperature
                        color: '#FF8000'
                        show_indicator: true
                  - type: custom:mini-graph-card
                    name: Outside
                    icon: "${states['sensor.dark_sky_temperature'].state > 15 ? 'fas:thermometer-half' : 'fas:thermometer-quarter'}"
                    name_adaptive_color: true
                    icon_adaptive_color: true
                    more_info: false
                    height: 150
                    line_width: 4
                    hours_to_show: 24
                    points_per_hour: 0.50
                    group: false
                    hour24: true
                    animate: true
                    decimals: 1
                    align_state: center
                    show:
                      name: true
                      icon: true
                      state: true
                      graph: false
                      fill: false
                      points: false
                      legend: false
                      extrema: true
                      labels: false
                    entities:
                      - entity: sensor.dark_sky_temperature
                        color: '#FF8000'
                        show_indicator: true
                  - type: custom:mini-graph-card
                    name: Outside
                    icon: "${states['sensor.dark_sky_temperature'].state > 15 ? 'fas:thermometer-half' : 'fas:thermometer-quarter'}"
                    name_adaptive_color: true
                    icon_adaptive_color: true
                    more_info: false
                    height: 150
                    line_width: 4
                    hours_to_show: 24
                    points_per_hour: 0.50
                    group: false
                    hour24: true
                    animate: true
                    decimals: 1
                    align_state: center
                    show:
                      name: true
                      icon: true
                      state: true
                      graph: false
                      fill: false
                      points: false
                      legend: false
                      extrema: true
                      labels: false
                    entities:
                      - entity: sensor.dark_sky_temperature
                        color: '#FF8000'
                        show_indicator: true
              - type: custom:mini-graph-card
                name: Temperature 48h
                icon: fas:thermometer-half
                name_adaptive_color: true
                icon_adaptive_color: true
                more_info: false
                group: false
                height: 150
                line_width: 4
                hours_to_show: 24
                points_per_hour: 0.5
                hour24: true
                animate: true
                decimals: 1
                align_state: center
                show:
                    name: false
                    icon: false
                    state: false
                    graph: line
                    fill: false
                    points: false
                    legend: true
                    extrema: false
                    labels: false
                entities:
                    - entity: sensor.dark_sky_temperature
                      name: Outside
                      color: '#FF8000'
                    - entity: sensor.dark_sky_temperature
                      name: Master Bedroom
                      color: '#0080FF'
                    - entity: sensor.dark_sky_temperature
                      name: Living Room
                      color: '#FF3333'
                    - entity: sensor.dark_sky_temperature
                      name: Office
                      color: '#7F00FF'
                    - entity: sensor.dark_sky_temperature
                      name: Bedroom
                      color: '#00FF00'
                    - entity: sensor.dark_sky_temperature
                      name: Bathroom
                      color: '#33FF99'
```

Screenshot with the problem:
![image](https://user-images.githubusercontent.com/9599441/54610964-fda69200-4a4d-11e9-8564-5269d2f45300.png)

Screenshot without the problem:
![image](https://user-images.githubusercontent.com/9599441/54611003-1020cb80-4a4e-11e9-99f4-0a9ca268e698.png)

Let me know if you need further info :)
