### ISSUE TITLE
Something related to `not available` state in templates 

### ISSUE THREAD

**Issue by fantomnotabene** [custom-cards/config-template-card#9]
I have something like this:
```yaml
show_header_toggle: false
type: 'custom:hui-entities-card'
entities:
  - name: Ceiling
    secondary_info: last-changed
    entity: switch.ceiling_bedroom
  - icon: >-
      ${states['light.ls1'].state === 'off' ? 'mdi:led-off' :
      'mdi:led-on'}
    toggle: 'yes'
    secondary_info: last-changed
    type: 'custom:slider-entity-row'
    entity: light.ls1
  - name: Lamp
    toggle: 'yes'
    secondary_info: last-changed
    type: 'custom:slider-entity-row'
    entity: light.lamp_bedroom
  - secondary_info: last-changed
    entity: switch.homey_led_ring
```
And when `light.ls1` is not available, the whole card is not displaying. There is something about template processing inside of `icon:`, I think. Because if I remove the line with template, the whole card appears back again.
